data_sources:
  clarity_data:
    path: data\raw\clarity_underwriting_variables.csv
    type: csv
  loan_data:
    path: data\raw\loan.csv
    type: csv
  payment_data:
    path: data\raw\payment.csv
    type: csv
data_storage:
  deployment_dir: models\production
  evaluation_dir: models\evaluation
  features_dir: data\features
  models_dir: models\training
  monitoring_dir: data\monitoring
  processed_data_dir: data\processed
  raw_data_dir: data\raw
deployment:
  prediction_threshold: 0.5
  production_model_path: models/production
  registry_path: models/registry.json
  risk_categorization:
    high_risk_min: 0.7
    low_risk_max: 0.3
    medium_risk_max: 0.7
  thresholds:
    improvement_threshold: 0.01
    min_accuracy: 0.6
    min_precision: 0.5
    min_r2: 0.3
evaluation:
  generate_shap: true
  primary_metric: r2
  risk_thresholds:
    high_risk_min: 0.7
    low_risk_max: 0.3
  secondary_metrics:
  - mse
  - mae
feature_engineering:
  categorical_encoding: target
  create_interactions: true
  drop_low_variance: true
  polynomial_features: true
  polynomial_features_list:
  - loanAmount
  - apr
  - clearfraudscore
  variance_threshold: 0.02
logging:
  detailed_risk_logging: true
  log_dir: logs
  log_level: INFO
model:
  hyperparameters:
    colsample_bytree: 0.8
    learning_rate: 0.05
    max_depth: 10
    metric: mse
    min_child_samples: 30
    n_estimators: 200
    num_leaves: 50
    objective: regression
    random_state: 42
    reg_alpha: 0.1
    reg_lambda: 0.1
    subsample: 0.8
  task: regression
  type: lightgbm
monitoring:
  checks:
  - data_drift
  - performance_degradation
  - risk_distribution_shift
  create_dashboard: true
  frequency: daily
  reference_data_path: data/monitoring/reference_data
  save_reference_data: true
  thresholds:
    categorical_drift_threshold: 0.15
    drift_threshold: 0.15
    ks_threshold: 0.15
    performance:
      max_mae_increase: 0.03
      max_mse_increase: 0.05
      min_r2: 0.3
      relative_degradation_threshold: -0.1
target_column: target
training:
  cv_folds: 5
  random_seed: 42
  sampling_strategy: risk_based
  stratify: false
  test_size: 0.2
